import os
from registry import get_configs_dir, get_docker_configs_dir


def generate_nginx_config(project, port, domain, https=False, key_path=None, cert_path=None):
    configs_dir = get_configs_dir()
    config_path = configs_dir / f"{domain}.conf"

    lines = []
    lines.append(f"# VHost: {project} -> localhost:{port}")
    lines.append(f"# Generated by vhost-cli")
    lines.append("")

    if https and key_path and cert_path:
        lines.append("server {")
        lines.append(f"    listen 80;")
        lines.append(f"    server_name {domain};")
        lines.append(f"    return 301 https://$host$request_uri;")
        lines.append("}")
        lines.append("")
        lines.append("server {")
        lines.append(f"    listen 443 ssl http2;")
        lines.append(f"    server_name {domain};")
        lines.append("")
        lines.append(f"    ssl_certificate {cert_path};")
        lines.append(f"    ssl_certificate_key {key_path};")
        lines.append(f"    ssl_protocols TLSv1.2 TLSv1.3;")
        lines.append(f"    ssl_ciphers HIGH:!aNULL:!MD5;")
        lines.append("")
        lines.append(f"    location / {{")
        lines.append(f"        proxy_pass http://localhost:{port};")
        lines.append(f"        proxy_set_header Host $host;")
        lines.append(f"        proxy_set_header X-Real-IP $remote_addr;")
        lines.append(f"        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;")
        lines.append(f"        proxy_set_header X-Forwarded-Proto $scheme;")
        lines.append(f"    }}")
        lines.append("}")
    else:
        lines.append("server {")
        lines.append(f"    listen 80;")
        lines.append(f"    server_name {domain};")
        lines.append("")
        lines.append(f"    location / {{")
        lines.append(f"        proxy_pass http://localhost:{port};")
        lines.append(f"        proxy_set_header Host $host;")
        lines.append(f"        proxy_set_header X-Real-IP $remote_addr;")
        lines.append(f"        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;")
        lines.append(f"        proxy_set_header X-Forwarded-Proto $scheme;")
        lines.append(f"    }}")
        lines.append("}")

    content = "\n".join(lines) + "\n"
    with open(config_path, "w", encoding="utf-8") as f:
        f.write(content)

    return str(config_path)


def generate_caddy_config(project, port, domain, https=False, key_path=None, cert_path=None):
    configs_dir = get_configs_dir()
    config_path = configs_dir / f"{domain}.Caddyfile"

    lines = []
    lines.append(f"# VHost: {project} -> localhost:{port}")
    lines.append(f"# Generated by vhost-cli")
    lines.append("")

    if https and key_path and cert_path:
        lines.append(f"{domain} {{")
        lines.append(f"    tls {cert_path} {key_path}")
        lines.append(f"    reverse_proxy localhost:{port}")
        lines.append(f"}}")
    else:
        lines.append(f"{domain}:80 {{")
        lines.append(f"    reverse_proxy localhost:{port}")
        lines.append(f"}}")

    content = "\n".join(lines) + "\n"
    with open(config_path, "w", encoding="utf-8") as f:
        f.write(content)

    return str(config_path)


def generate_docker_compose_override(project, port, domain, container_name=None, service_name=None):
    docker_dir = get_docker_configs_dir()
    config_path = docker_dir / f"{domain}.docker-compose.yml"

    if container_name is None:
        container_name = project
    if service_name is None:
        service_name = project

    lines = []
    lines.append(f"# Docker Compose Override for {project}")
    lines.append(f"# Generated by vhost-cli")
    lines.append(f"# Usage: docker compose -f docker-compose.yml -f {config_path.name} up")
    lines.append("")

    lines.append("version: '3.8'")
    lines.append("")
    lines.append("services:")
    lines.append(f"  {service_name}:")
    lines.append(f"    container_name: {container_name}")
    lines.append(f"    ports:")
    lines.append(f'      - "{port}:{port}"')
    lines.append(f"    environment:")
    lines.append(f'      - VIRTUAL_HOST={domain}')
    lines.append(f"    networks:")
    lines.append(f"      - vhost-network")
    lines.append("")
    lines.append("networks:")
    lines.append("  vhost-network:")
    lines.append("    name: vhost-network")
    lines.append("    driver: bridge")

    content = "\n".join(lines) + "\n"
    with open(config_path, "w", encoding="utf-8") as f:
        f.write(content)

    return str(config_path)


def remove_config(domain):
    configs_dir = get_configs_dir()
    for ext in [".conf", ".Caddyfile"]:
        config_path = configs_dir / f"{domain}{ext}"
        if config_path.exists():
            config_path.unlink()

    docker_dir = get_docker_configs_dir()
    docker_config_path = docker_dir / f"{domain}.docker-compose.yml"
    if docker_config_path.exists():
        docker_config_path.unlink()


def generate_config(project, port, proxy="nginx", https=False, key_path=None, cert_path=None, docker=False):
    domain = f"{project}.test"

    if proxy == "caddy":
        config_path = generate_caddy_config(project, port, domain, https, key_path, cert_path)
    else:
        config_path = generate_nginx_config(project, port, domain, https, key_path, cert_path)

    docker_config_path = None
    if docker:
        docker_config_path = generate_docker_compose_override(project, port, domain)

    return config_path, docker_config_path


def preview_config(project, port, proxy="nginx", https=False, docker=False):
    domain = f"{project}.test"
    configs_dir = get_configs_dir()
    result = {
        "domain": domain,
        "hosts_entry": f"127.0.0.1 {domain}",
    }

    if proxy == "caddy":
        result["config_path"] = str(configs_dir / f"{domain}.Caddyfile")
    else:
        result["config_path"] = str(configs_dir / f"{domain}.conf")

    if https:
        from registry import get_certs_dir
        certs_dir = get_certs_dir()
        result["key_path"] = str(certs_dir / domain / f"{domain}.key")
        result["cert_path"] = str(certs_dir / domain / f"{domain}.crt")

    if docker:
        docker_dir = get_docker_configs_dir()
        result["docker_config_path"] = str(docker_dir / f"{domain}.docker-compose.yml")

    return result


def preview_delete(project):
    domain = f"{project}.test"
    configs_dir = get_configs_dir()
    result = {
        "domain": domain,
        "hosts_entry": f"127.0.0.1 {domain}",
        "files_to_remove": [],
    }

    for ext in [".conf", ".Caddyfile"]:
        config_path = configs_dir / f"{domain}{ext}"
        if config_path.exists():
            result["files_to_remove"].append(str(config_path))

    from registry import get_certs_dir, get_docker_configs_dir
    certs_dir = get_certs_dir()
    cert_domain_dir = certs_dir / domain
    if cert_domain_dir.exists():
        for f in cert_domain_dir.iterdir():
            result["files_to_remove"].append(str(f))

    docker_dir = get_docker_configs_dir()
    docker_config = docker_dir / f"{domain}.docker-compose.yml"
    if docker_config.exists():
        result["files_to_remove"].append(str(docker_config))

    return result